### ISSUE TITLE
Arbitrary page length for mail list

### ISSUE THREAD

**Issue by AleCandido** [soywod/himalaya.vim#3]
Essentially what is in the title, just adding a **user configurable variable** and using it here:
https://github.com/soywod/himalaya.vim/blob/52912cdab36911f09832a7cfffc15c7fe1ba3150/autoload/himalaya/msg.vim#L28
just adding `. " --size " . g:himalaya_page_length` or something like this.

A **further improvement** would be to have vim determine it by itself, e.g.
- if `g:himalaya_page_length` is set to its default value (say 0)
- use as value `winheight(0)`

or something like this.

---

Thank you for the project, I know it's still new but I like the idea.
I tried `iris.vim` but I've never managed to make it run, probably for issues with the `IMAPClient`, but it does not matter: I'm looking for this one now.

**Comment by soywod** [comment]
It's a good point, I totally forgot this parameter. I think it's better to add a parameter `default-page-size` in the CLI config instead. I prefer to have as few logic as possible in this Vim plugin, it should remain a simple view over the CLI.

---

Thank you for the issue, it's thanks to them I can improve the tool. The project is still new indeed, but it's in active development. I aim to release a v1 ASAP. `iris.vim` was a good experiment, I realised that there is a real need (I didn't expect so much stars and support). But I also realised that it's not a good idea to keep the logic front side (+ Python lacks of solidity for such a project). Feel free to open as many issues as you want :) you can also use the new GitHub feature "Discussions" if needed.

**Comment by AleCandido** [comment]
I perfectly agree to decouple (with the obvious benefit that the backend we'll integrate, rather than being limited to vim), and since there is the global configuration a parameter for the length should fit there.

Nevertheless I would go for the window size/adaptive length in vim (as a second step), because this is a vim specific thing. 

Of course whatever it comes it's appreciated, thank you for your effort :)

**Comment by soywod** [comment]
> Nevertheless I would go for the window size/adaptive length in vim (as a second step), because this is a vim specific thing.

Well, I could introduce a `parent-height` variable in the config, this way it adapts (no matter the frontend) to the parent's height. I will keep in mind for the future ;)

**Comment by soywod** [comment]
I move the issue [there](https://github.com/soywod/himalaya/issues/46) since I'm merging the vim plugin with the CLI repo.
