### ISSUE TITLE
Latency and friction

### ISSUE THREAD

**Issue by AleCandido** [soywod/himalaya.vim#4]
Sorry to bother you with issues, I'm finding them while trying it.

There are a couple of things that are quite annoying, even if not preventing usage:
- every time you change view he asked to press ENTER
  - I know it's probably because you are running a shell program and I don't know how to solve it
- every time you change view you have to wait a bit
  - I believe it's because it's downloading every time all the information, maybe it can be solved by caching a bit and update asynchronously

Of course they are just ux improvements.

**Comment by soywod** [comment]
> * every time you change view he asked to press ENTER

This may be because of your Vim cmd height. A quick fix could be to increase it `set cmdheight=3`, but I will check how to change this.

> * every time you change view you have to wait a bit

Indeed, a call is made each time you do an action. The quick fix is to use an offline IMAP synchroniser (like [isync](https://isync.sourceforge.io/) or [OfflineIMAP](https://github.com/OfflineIMAP/offlineimap)). This way you remove the network latency. I will see how to add cache to improve UX.

**Comment by AleCandido** [comment]
> This may be because of your Vim cmd height. The quick fix is to increase it with set cmdheight=3. I will check how to prevent logs showing on more than 1 line.

This I will try, indeed I keep `cmdheight=1`, maybe I can search a bit.

> The quick fix is to use an offline IMAP synchroniser (like isync or OfflineIMAP). 

Perfect, if you have any working setup, with external utilities, can you share some details?

**Comment by soywod** [comment]
> Perfect, if you have any working setup, with external utilities, can you share some details?

I great starting point is[mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard), which sets up with ease a isync/msmtp/neomutt environment.

**Comment by soywod** [comment]
For now, the tool can only fetch messages from a local/remote IMAP server. But it could be great to fetch from a local [Maildir](https://en.wikipedia.org/wiki/Maildir) folder, this way no latency!

**Comment by AleCandido** [comment]
I don't have your experience with mail protocols, but while waiting for some native implementation, is there any way to have `himalaya` itself spawning a third-party IMAP server locally to interact with?
Or maybe is it as expensive as implementing Maildir support?

**Comment by soywod** [comment]
I need to read more about Maildir, but it seems to be just files in folders. So it should be easier and faster than a local IMAP server. I'm analysing a Rust crate that parses a Maildir, I will let you know!
For now I try to focus on other "mandatory" features (the one I miss to use Himalaya in production), like copy/move/delete a msg, add attachments when writting a msg etc

**Comment by AleCandido** [comment]
Perfectly fine!

**Comment by soywod** [comment]
https://github.com/soywod/himalaya/issues/43
